// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt56D3EUKAMMM3yi5yxTz-qqtAy8-y3VI',
    appId: '1:971917852955:web:e4525c285adebe0b2893be',
    messagingSenderId: '971917852955',
    projectId: 'chattingapp-8fe39',
    authDomain: 'chattingapp-8fe39.firebaseapp.com',
    storageBucket: 'chattingapp-8fe39.appspot.com',
    measurementId: 'G-W9FL3K16KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-HPg9LhgQiIYKDuOi9fzDrWDyyA2nyQ',
    appId: '1:971917852955:android:f1b6e68c49e40e542893be',
    messagingSenderId: '971917852955',
    projectId: 'chattingapp-8fe39',
    storageBucket: 'chattingapp-8fe39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGQU1bd6AO6kRcIBoJlYmOSgMUcnMlBSM',
    appId: '1:971917852955:ios:4480d79b51c3e9d82893be',
    messagingSenderId: '971917852955',
    projectId: 'chattingapp-8fe39',
    storageBucket: 'chattingapp-8fe39.appspot.com',
    iosBundleId: 'com.example.chattingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGQU1bd6AO6kRcIBoJlYmOSgMUcnMlBSM',
    appId: '1:971917852955:ios:4480d79b51c3e9d82893be',
    messagingSenderId: '971917852955',
    projectId: 'chattingapp-8fe39',
    storageBucket: 'chattingapp-8fe39.appspot.com',
    iosBundleId: 'com.example.chattingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt56D3EUKAMMM3yi5yxTz-qqtAy8-y3VI',
    appId: '1:971917852955:web:023ab54351facc122893be',
    messagingSenderId: '971917852955',
    projectId: 'chattingapp-8fe39',
    authDomain: 'chattingapp-8fe39.firebaseapp.com',
    storageBucket: 'chattingapp-8fe39.appspot.com',
    measurementId: 'G-PR35H59Y0C',
  );

}